# Generated by Django 4.2.2 on 2023-06-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_userprofile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
    ]
